### ISSUE TITLE
Sync Deletes pre-existing files in target folder, without warning or confirmation or Recycle Bin.

### ISSUE THREAD

**Issue by gbarwis** [BlueGreenMagick/sync-excel-with-anki#1]
Syncing Anki -> Excel removes all files from target directory, recursively, except for those related to the sync... and does this without warning, without confirmation, bypassing Windows Recycle Bin, and without (AFAICT) documentation of this behavior. I lost about a thousand work-in-progress files from Photoshop, Premiere, and Python from my "D://Working" folder.

The user can avoid this by creating a _new_ folder for the sync add-in to use, but this behavior should at the very least be clearly documented as part of installation instructions.

**Comment by BlueGreenMagick** [comment]
I am really sorry, there really should have been a confirmation popup for deleting all other files. I hadn't thought of other files being in the sync directory. This is being addressed, and in the next update, only other excel files will be deleted after confirmation.

**Comment by gbarwis** [comment]
> I am really sorry, there really should have been a confirmation popup for deleting all other files. I hadn't thought of other files being in the sync directory. This is being addressed, and in the next update, only other excel files will be deleted after confirmation.

Thanks for the quick response!

**Comment by gbarwis** [comment]
Inadvertently closed, sorry... Thanks for the quick response, and nice work on a super-handy (and my new favorite) Anki add-in!

**Comment by BlueGreenMagick** [comment]
I uploaded the new version to Ankiweb. Should be good now.
