### ISSUE TITLE
Anki freezes after sync either way.

### ISSUE THREAD

**Issue by walternue** [BlueGreenMagick/sync-excel-with-anki#14]
Hi, the addon looks marvellous and I am eager to try it. I have some issues I cannot overcome though. 

When I try to sync from Excel to Anki there is a pop-up window telling me: 2 notes total, 0 to modify, 30 to add, 0 to delete. Proceed? I hit Yes and now there are two pop-up windows, the back one has a title "Excel Sync Done" the front one says "Excel -> Anki Sync " and anki freezes. When I force quit Anki, Anki decks are not modified.

When I try to sync from Anki to Excel anki freezes with "Loking at directories" window. When I force quit Anki, Excel file **is** modified.

Can you help me resolve this please?
Walter

![image](https://user-images.githubusercontent.com/38569131/105491796-31404c00-5cb7-11eb-9d73-a359fe3c2f92.png)
![image](https://user-images.githubusercontent.com/38569131/105492030-9300b600-5cb7-11eb-8fd4-d2b5caed11d6.png)
![image](https://user-images.githubusercontent.com/38569131/105492049-9dbb4b00-5cb7-11eb-9b45-5a3dd55e2b9b.png)

**Comment by BlueGreenMagick** [comment]
Could you post what Anki version you are using? And check if you have available update for this addon?

**Comment by BlueGreenMagick** [comment]
Fixed!

**Comment by walternue** [comment]
Sorry I didn't reply in time. Thank you very much for fixing this!
