### ISSUE TITLE
Stuck on "Looking at directories"

### ISSUE THREAD

**Issue by Neribr** [BlueGreenMagick/sync-excel-with-anki#15]
I use Anki 2.35 and when I click "Anki to Excel" it just gets stuck on 'Looking at directories'.

I tried making a new profile with only one card, and I still have the same problem.

![image](https://user-images.githubusercontent.com/22844260/105616115-dd169400-5daa-11eb-86d2-45aa36b3f74d.png)

I tried disabling all other addons, no success.
![image](https://user-images.githubusercontent.com/22844260/105616169-439bb200-5dab-11eb-8d19-e873f8f9d048.png)

This is my version:
![image](https://user-images.githubusercontent.com/22844260/105616213-b3aa3800-5dab-11eb-9d59-1e0a71394220.png)

Maybe it will work if I upgrade to 2.38? What can I do?

......................

edit: I made a folder with the name of the tag I want to sync... created a card with that tag... clicked "Anki to Excel"...
![image](https://user-images.githubusercontent.com/22844260/105616322-6ed2d100-5dac-11eb-918e-4b0b089aa0b4.png)

But it's still stuck.

......................

edit 2: after reading this comment
![image](https://user-images.githubusercontent.com/22844260/105616481-98d8c300-5dad-11eb-900f-7efe448c0630.png)

I actually understood how it works, and I got it to write the excel sheet:

![image](https://user-images.githubusercontent.com/22844260/105616475-91191e80-5dad-11eb-9a95-912af6ca47e8.png)

But now I'm stuck on the sync part:
![image](https://user-images.githubusercontent.com/22844260/105616489-ad1cc000-5dad-11eb-8508-08a28d5bd42c.png)

I guess that now I'm having the same issue as this person:
![image](https://user-images.githubusercontent.com/22844260/105616512-fec54a80-5dad-11eb-8a08-ade4ee9996ad.png)

**Comment by BlueGreenMagick** [comment]
Should be fixed in the latest version!
