### ISSUE TITLE
Does this plugin work with audio?

### ISSUE THREAD

**Issue by rlam3** [BlueGreenMagick/sync-excel-with-anki#19]
Does this plugin work with audio? I have audio already set into the cards. Do I have to reload all audio if I were to edit and import?

**Comment by BlueGreenMagick** [comment]
To my best knowledge, audio like `[[audio:xxx]]` should be fine! The card just stores the audio file name, which wouldn't be deleted when you sync out.

You should probably test it out beforehand though.
