### ISSUE TITLE
 Anki v2.1.52 anki>excel

### ISSUE THREAD

**Issue by bifny** [BlueGreenMagick/sync-excel-with-anki#20]
Hello,
I want to export notes from anki to excel.
My anki is  v2.1.52.
Might it work?
Thank you so much.

**Comment by BlueGreenMagick** [comment]
If it's just one-time export, I think [this other addon](https://ankiweb.net/shared/info/1967530655) should work.

If you need to sync constantly and want to use this add-on, you may need to downgrade down to 2.1.38. It's the last version I tested this add-on on, and I don't know if it still works on latest Anki versions. You can download older versions [here](https://github.com/ankitects/anki/releases).

**Comment by bifny** [comment]
Hello,
Thank you for helping.
You solved a big problem for me.
I’m very grateful.
                Tiffany


BlueGreenMagick ***@***.***> 於 2022年6月5日 週日 下午11:23寫道：
