### ISSUE TITLE
"Anki Excel Sync" export one card, import the same exported file and get this error

### ISSUE THREAD

**Issue by JulioFalcon-Nodos** [BlueGreenMagick/sync-excel-with-anki#22]
Dear Colleagues,

I’m having a problem with “Anki Excel Sync”, export a file and import the same file, without opening and get the error.

Of course I try to import before a file with a lot of cards, but get the same error, so I tried this file as is and also get the error.

I don’t see if I can attach a file, to share the excel file

Thanks in advance

The error is:

Información de depuración:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-23 23:13:43

Caught exception:
Traceback (most recent call last):
File “aqt.taskman”, line 122, in _on_closures_pending
File “aqt.taskman”, line 71, in
File “aqt.taskman”, line 90, in wrapped_done
File “aqt.sync”, line 117, in on_future_done
File “aqt.main”, line 970, in on_collection_sync_finished
File “aqt.main”, line 596, in after_sync
File “aqt.mediasync”, line 125, in show_diag_until_finished
File “aqt.main”, line 593, in after_media_sync
File “C:\Users\julio\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py”, line 253, in on_unload
syncfunc()
File “C:\Users\julio\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py”, line 425, in _e2a_sync
raise e
File “C:\Users\julio\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py”, line 334, in _e2a_sync
raise DeckNameDoesNotExistError(decknm)
File “C:\Users\julio\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\errors.py”, line 149, in init
super.init()
TypeError: descriptor ‘init’ of ‘super’ object needs an argument

Julio Falcón
Systems & Software Engineer

**Comment by JulioFalcon-Nodos** [comment]
This is the exported file, I'm using also the **multiple choice with 12 options** "https://ankiweb.net/shared/info/1573325751" complement, the first time it works, I can export, add a new line and import, but I when I add a lot a lines (29) it cannot be imported, I review the created file, but no way, so I copy it on another directory and delete all in the directory configured to import/export, export the the cards again, try to import and get the error

[JFLCreatioCert.xlsx](https://github.com/BlueGreenMagick/sync-excel-with-anki/files/10087064/JFLCreatioCert.xlsx)

**Comment by BlueGreenMagick** [comment]
In the add-on config, make sure 'new-deck' is a deck name that exists.

**Comment by soph104** [comment]
Worked for me, thank you!
