### ISSUE TITLE
Error while opening after Anki's update

### ISSUE THREAD

**Issue by CirclesConfusion** [BlueGreenMagick/sync-excel-with-anki#25]
Hi,

After the recent Anki update (Version ⁨2.1.66 (70506aeb)⁩), there is an error appearing while opening the add-on.

**Error message while opening Anki -> Excel**
> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
> Platform: Windows-10-10.0.19045
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-08-30 21:22:39
> Add-ons possibly involved: ⁨Anki Excel Sync⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "aqt.sync", line 117, in on_future_done
>   File "aqt.main", line 1031, in on_collection_sync_finished
>   File "aqt.main", line 632, in after_sync
>   File "aqt.mediasync", line 125, in show_diag_until_finished
>   File "aqt.main", line 629, in after_media_sync
>   File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 253, in on_unload
>     syncfunc()
>   File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 564, in _a2e_sync
>     raise e
>   File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 446, in _a2e_sync
>     files, super_tags = self.excel_files_in_dir(dirc)
>   File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 47, in excel_files_in_dir
>     super_tags = self.get_super_dirs(directory)
>   File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 38, in get_super_dirs
>     for name in os.listdir(dirc):
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:/Somedirectory you want to save excel files'

#############################

**Error while opening Excel -> Anki**
> ERROR!
> An error occured during sync.
> Depending on the error, some notes may have been synced while others weren't.
> Please sync again after fixing the issue.
> 
> 
> Error Log
> --------------------------------------------------
> 
> 
> 
>
> Detailed Error Log
> --------------------------------------------------
> Traceback (most recent call last):
> File "C:\Users\duo\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 332, in _e2a_sync
> raise DidNotConfigureDirectoryError()
> 1832015432.ankiExcelSync.errors.DidNotConfigureDirectoryError: <br>

**Comment by BlueGreenMagick** [comment]
I think you forgot to edit the add-on configuration to put in the directory of your excel files
