### ISSUE TITLE
Update for Anki 2.1.26

### ISSUE THREAD

**Issue by RonilPatel7** [BlueGreenMagick/sync-excel-with-anki#8]
Would you be able to update the add on to work for v2.1.26; I would be ale to pay a commission via PayPal/Venmo/Zelle? Please fell to message me! Thank you

**Comment by BlueGreenMagick** [comment]
I've just uploaded an update that should support v2.1.26. Can you try it out and tell me if it works? Thanks.

**Comment by RonilPatel7** [comment]
it is working well so far thak you

PS I typically have my first field as note ID & use this add on to fill it in (https://ankiweb.net/shared/info/1672832404); would you be able to modify your code to allow anki to import rows that have a blank first field? Thank you

**Comment by BlueGreenMagick** [comment]
Great to hear that! Regarding having blank first row, I'll add that to my to-do list.
